######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 25 15:13:59 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

# Input
HEADERS += Chessman.h def.h Image.h Point.h Yi.h
SOURCES += Chessman.cpp Image.cpp main.cpp Point.cpp Yi.cpp
